- type: gameMapPool
  id: CorvaxDefaultMapPool
  maps:
  # Highpop
  - CorvaxDelta
  - CorvaxAvrite
  - CorvaxAstra
  - CorvaxPilgrim
  - CorvaxGlacier
  # Midpop
  - CorvaxPaper
  - CorvaxOutpost
  - CorvaxAwesome
  # Lowpop
  - CorvaxSilly
  - CorvaxMaus
  - CorvaxTushkan
